In [ ]:
Reshma Puchakayala
700766173

In [57]:
# Employee class
class Employee:

    employee_count = 0

    def __init__(self, name, family, salary, department):

        self.name = name
        self.salary = salary
        self.department = department
        self.family = family


        Employee.employee_count += 1

    def average_salary(list_employees):

        total_salary = sum(e.salary for e in list_employees)
        return total_salary / len(list_employees) if list_employees else 0


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, work_hours):
        # Initialize the base class (Employee) with common attributes
        super().__init__(name, family, salary, department)
        self.work_hours = work_hours


emp1 = Employee("Rosie", "single", 840000, "Finance")
emp2 = Employee("Mounika", "Single", 850000, "HR")
fulltime_emp1 = FulltimeEmployee("Revanth", "single", 950000, "IT", 40)
fulltime_emp2 = FulltimeEmployee("Suresh", "Single", 1050000, "Marketing", 45)


print(f"Total employees in the company: {Employee.employee_count}")


employees = [emp1, emp2, fulltime_emp1, fulltime_emp2]

fulltime_employees = [e for e in employees if isinstance(e, FulltimeEmployee)]


average_salary_emp = Employee.average_salary(employees)
print(f"Average Salary of all employees: {average_salary_emp}")



average_fulltime_salary = Employee.average_salary(fulltime_employees)
print(f"Average Salary of Fulltime Employees: {average_fulltime_salary}")


Total employees in the company: 4
Average Salary of all employees: 922500.0
Average Salary of Fulltime Employees: 1000000.0


In this code I defined two classes, Employee and FulltimeEmployee.I created an Employee Class which represents a basic employee with attributes and methods for handling employee details such as name,salary,department,family,employee_count.I used a Constructor to initializes the employee's details and increments employee_count.Displays the employee's details (name, department, salary, and family status) then calculates the average salary of a list of employees.FulltimeEmployee Clas it extends the Employee class to represent full-time employees with additional attributes.it Inherits from Employee class, adding a work_hours attribute and overriding the display method to include work hours.

In [58]:
import numpy as np

random_vector = np.random.uniform(1, 20, 20)
print(random_vector)
matrix = random_vector.reshape(4, 5)
print("Random vector reshaped into 4x5 matrix:")
print(random_vector.reshape(4, 5))
max_indices = np.argmax(matrix, axis=1)
rows = np.arange(matrix.shape[0])
matrix[rows, max_indices] = 0

print("\nModified 4x5 matrix with maximum values replaced by 0:")
print(matrix)


[16.01974474  7.21191416 13.67869668 14.97311375 13.30294797 10.13680884
 16.50644176 15.05410672  2.86906675 14.75225009  1.97611857 11.19295998
 11.91803013  7.85858707 19.81731964  4.46261058 16.62869021 11.65890097
  7.82335267 12.02038506]
Random vector reshaped into 4x5 matrix:
[[16.01974474  7.21191416 13.67869668 14.97311375 13.30294797]
 [10.13680884 16.50644176 15.05410672  2.86906675 14.75225009]
 [ 1.97611857 11.19295998 11.91803013  7.85858707 19.81731964]
 [ 4.46261058 16.62869021 11.65890097  7.82335267 12.02038506]]

Modified 4x5 matrix with maximum values replaced by 0:
[[ 0.          7.21191416 13.67869668 14.97311375 13.30294797]
 [10.13680884  0.         15.05410672  2.86906675 14.75225009]
 [ 1.97611857 11.19295998 11.91803013  7.85858707  0.        ]
 [ 4.46261058  0.         11.65890097  7.82335267 12.02038506]]


This code uses NumPy to create and manipulate a 4x5 matrix.I genearted a vector of 20 random float values between 1 and 20.Then the vector is reshaped into a 4x5 matrix.I found a maximum values by the column index of the maximum value in each row is identified using np.argmax.Then replaced Maximum with 0: The maximum value in each row is replaced with 0 using advanced indexing.Then the results got displayed. The original reshaped matrix and the modified matrix are printed.

